/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShortcodeRouteImport } from './routes/$shortcode'
import { Route as IndexRouteImport } from './routes/index'

const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortcodeRoute = ShortcodeRouteImport.update({
  id: '/$shortcode',
  path: '/$shortcode',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$shortcode': typeof ShortcodeRoute
  '/login': typeof LoginRoute
  '/sso-callback': typeof SsoCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$shortcode': typeof ShortcodeRoute
  '/login': typeof LoginRoute
  '/sso-callback': typeof SsoCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$shortcode': typeof ShortcodeRoute
  '/login': typeof LoginRoute
  '/sso-callback': typeof SsoCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$shortcode' | '/login' | '/sso-callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$shortcode' | '/login' | '/sso-callback'
  id: '__root__' | '/' | '/$shortcode' | '/login' | '/sso-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShortcodeRoute: typeof ShortcodeRoute
  LoginRoute: typeof LoginRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$shortcode': {
      id: '/$shortcode'
      path: '/$shortcode'
      fullPath: '/$shortcode'
      preLoaderRoute: typeof ShortcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShortcodeRoute: ShortcodeRoute,
  LoginRoute: LoginRoute,
  SsoCallbackRoute: SsoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
