// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUserLinks = `-- name: CountUserLinks :one
SELECT COUNT(DISTINCT l.id) as total
FROM links l
WHERE l.user_id = $1 
  AND l.deleted_at IS NULL
  AND (
    -- If is_active filter is NULL, show all links
    $2::boolean IS NULL
    OR (
      -- Active filter: is_active = true AND (no expiration OR not expired)
      $2::boolean = true
      AND COALESCE(l.is_active, true) = true
      AND (l.expires_at IS NULL OR l.expires_at > NOW())
    )
    OR (
      -- Inactive filter: is_active = false OR expired
      $2::boolean = false
      AND (
        COALESCE(l.is_active, true) = false
        OR (l.expires_at IS NOT NULL AND l.expires_at <= NOW())
      )
    )
  )
  AND (
    $3::uuid[] IS NULL 
    OR l.id IN (
      SELECT DISTINCT lt.link_id
      FROM link_tags lt
      WHERE lt.tag_id = ANY($3::uuid[])
    )
  )
`

type CountUserLinksParams struct {
	UserID   string      `json:"user_id"`
	IsActive *bool       `json:"is_active"`
	TagIds   []uuid.UUID `json:"tag_ids"`
}

func (q *Queries) CountUserLinks(ctx context.Context, arg CountUserLinksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserLinks, arg.UserID, arg.IsActive, arg.TagIds)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const deleteLink = `-- name: DeleteLink :one
UPDATE links
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, shortcode, original_url, is_active, expires_at, created_at, updated_at
`

type DeleteLinkParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"user_id"`
}

type DeleteLinkRow struct {
	ID          uuid.UUID        `json:"id"`
	Shortcode   string           `json:"shortcode"`
	OriginalUrl string           `json:"original_url"`
	IsActive    bool             `json:"is_active"`
	ExpiresAt   pgtype.Timestamp `json:"expires_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) DeleteLink(ctx context.Context, arg DeleteLinkParams) (DeleteLinkRow, error) {
	row := q.db.QueryRow(ctx, deleteLink, arg.ID, arg.UserID)
	var i DeleteLinkRow
	err := row.Scan(
		&i.ID,
		&i.Shortcode,
		&i.OriginalUrl,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinkByIdAndUser = `-- name: GetLinkByIdAndUser :one
SELECT id, shortcode, original_url, expires_at, is_active, created_at, updated_at
FROM links
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
LIMIT 1
`

type GetLinkByIdAndUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"user_id"`
}

type GetLinkByIdAndUserRow struct {
	ID          uuid.UUID        `json:"id"`
	Shortcode   string           `json:"shortcode"`
	OriginalUrl string           `json:"original_url"`
	ExpiresAt   pgtype.Timestamp `json:"expires_at"`
	IsActive    bool             `json:"is_active"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetLinkByIdAndUser(ctx context.Context, arg GetLinkByIdAndUserParams) (GetLinkByIdAndUserRow, error) {
	row := q.db.QueryRow(ctx, getLinkByIdAndUser, arg.ID, arg.UserID)
	var i GetLinkByIdAndUserRow
	err := row.Scan(
		&i.ID,
		&i.Shortcode,
		&i.OriginalUrl,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinkByIdAndUserWithTags = `-- name: GetLinkByIdAndUserWithTags :one
SELECT 
    l.id,
    l.shortcode,
    l.original_url,
    l.expires_at,
    l.is_active,
    l.created_at,
    l.updated_at,
    COALESCE(
        json_agg(
            json_build_object(
                'id', t.id,
                'name', t.name,
                'created_at', t.created_at
            )
        ) FILTER (WHERE t.id IS NOT NULL),
        '[]'::json
    ) as tags
FROM links l
LEFT JOIN link_tags lt ON l.id = lt.link_id
LEFT JOIN tags t ON lt.tag_id = t.id
WHERE l.id = $1 
  AND l.user_id = $2 
  AND l.deleted_at IS NULL
GROUP BY l.id
`

type GetLinkByIdAndUserWithTagsParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"user_id"`
}

type GetLinkByIdAndUserWithTagsRow struct {
	ID          uuid.UUID        `json:"id"`
	Shortcode   string           `json:"shortcode"`
	OriginalUrl string           `json:"original_url"`
	ExpiresAt   pgtype.Timestamp `json:"expires_at"`
	IsActive    bool             `json:"is_active"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Tags        interface{}      `json:"tags"`
}

func (q *Queries) GetLinkByIdAndUserWithTags(ctx context.Context, arg GetLinkByIdAndUserWithTagsParams) (GetLinkByIdAndUserWithTagsRow, error) {
	row := q.db.QueryRow(ctx, getLinkByIdAndUserWithTags, arg.ID, arg.UserID)
	var i GetLinkByIdAndUserWithTagsRow
	err := row.Scan(
		&i.ID,
		&i.Shortcode,
		&i.OriginalUrl,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
	)
	return i, err
}

const getLinkByShortcodeAndUser = `-- name: GetLinkByShortcodeAndUser :one
SELECT 
    l.id,
    l.shortcode,
    l.original_url,
    l.expires_at,
    l.is_active,
    l.created_at,
    l.updated_at,
    COALESCE(
        json_agg(
            json_build_object(
                'id', t.id,
                'name', t.name,
                'created_at', t.created_at
            )
        ) FILTER (WHERE t.id IS NOT NULL),
        '[]'::json
    ) as tags
FROM links l
LEFT JOIN link_tags lt ON l.id = lt.link_id
LEFT JOIN tags t ON lt.tag_id = t.id
WHERE l.shortcode = $1 
  AND l.user_id = $2 
  AND l.deleted_at IS NULL
GROUP BY l.id
`

type GetLinkByShortcodeAndUserParams struct {
	Shortcode string `json:"shortcode"`
	UserID    string `json:"user_id"`
}

type GetLinkByShortcodeAndUserRow struct {
	ID          uuid.UUID        `json:"id"`
	Shortcode   string           `json:"shortcode"`
	OriginalUrl string           `json:"original_url"`
	ExpiresAt   pgtype.Timestamp `json:"expires_at"`
	IsActive    bool             `json:"is_active"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Tags        interface{}      `json:"tags"`
}

func (q *Queries) GetLinkByShortcodeAndUser(ctx context.Context, arg GetLinkByShortcodeAndUserParams) (GetLinkByShortcodeAndUserRow, error) {
	row := q.db.QueryRow(ctx, getLinkByShortcodeAndUser, arg.Shortcode, arg.UserID)
	var i GetLinkByShortcodeAndUserRow
	err := row.Scan(
		&i.ID,
		&i.Shortcode,
		&i.OriginalUrl,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
	)
	return i, err
}

const getLinkForRedirect = `-- name: GetLinkForRedirect :one
SELECT id, original_url
FROM links
WHERE shortcode = $1
AND deleted_at IS NULL
AND is_active = true
AND (expires_at IS NULL OR expires_at > NOW())
LIMIT 1
`

type GetLinkForRedirectRow struct {
	ID          uuid.UUID `json:"id"`
	OriginalUrl string    `json:"original_url"`
}

func (q *Queries) GetLinkForRedirect(ctx context.Context, shortcode string) (GetLinkForRedirectRow, error) {
	row := q.db.QueryRow(ctx, getLinkForRedirect, shortcode)
	var i GetLinkForRedirectRow
	err := row.Scan(&i.ID, &i.OriginalUrl)
	return i, err
}

const listUserLinks = `-- name: ListUserLinks :many
SELECT 
    l.id,
    l.shortcode,
    l.original_url,
    l.expires_at,
    l.is_active,
    l.created_at,
    l.updated_at,
    COALESCE(
        json_agg(
            json_build_object(
                'id', t.id,
                'name', t.name,
                'created_at', t.created_at
            )
        ) FILTER (WHERE t.id IS NOT NULL),
        '[]'::json
    ) as tags
FROM links l
LEFT JOIN link_tags lt ON l.id = lt.link_id
LEFT JOIN tags t ON lt.tag_id = t.id
WHERE l.user_id = $1 
  AND l.deleted_at IS NULL
  AND (
    -- If is_active filter is NULL, show all links
    $2::boolean IS NULL
    OR (
      -- Active filter: is_active = true AND (no expiration OR not expired)
      $2::boolean = true
      AND COALESCE(l.is_active, true) = true
      AND (l.expires_at IS NULL OR l.expires_at > NOW())
    )
    OR (
      -- Inactive filter: is_active = false OR expired
      $2::boolean = false
      AND (
        COALESCE(l.is_active, true) = false
        OR (l.expires_at IS NOT NULL AND l.expires_at <= NOW())
      )
    )
  )
GROUP BY l.id
HAVING (
    $3::uuid[] IS NULL 
    OR COUNT(CASE WHEN t.id = ANY($3::uuid[]) THEN 1 END) > 0
)
ORDER BY l.created_at DESC
LIMIT $5 OFFSET $4
`

type ListUserLinksParams struct {
	UserID   string      `json:"user_id"`
	IsActive *bool       `json:"is_active"`
	TagIds   []uuid.UUID `json:"tag_ids"`
	Offset   int32       `json:"offset"`
	Limit    int32       `json:"limit"`
}

type ListUserLinksRow struct {
	ID          uuid.UUID        `json:"id"`
	Shortcode   string           `json:"shortcode"`
	OriginalUrl string           `json:"original_url"`
	ExpiresAt   pgtype.Timestamp `json:"expires_at"`
	IsActive    bool             `json:"is_active"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Tags        interface{}      `json:"tags"`
}

func (q *Queries) ListUserLinks(ctx context.Context, arg ListUserLinksParams) ([]ListUserLinksRow, error) {
	rows, err := q.db.Query(ctx, listUserLinks,
		arg.UserID,
		arg.IsActive,
		arg.TagIds,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserLinksRow
	for rows.Next() {
		var i ListUserLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Shortcode,
			&i.OriginalUrl,
			&i.ExpiresAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryCreateLink = `-- name: TryCreateLink :one
INSERT INTO links (shortcode, original_url, user_id, expires_at)
SELECT $1::VARCHAR(20), $2::TEXT, $3::TEXT, $4
WHERE NOT EXISTS (
    SELECT 1 FROM links 
    WHERE shortcode = $1::VARCHAR(20) AND deleted_at IS NULL
)
RETURNING id, shortcode, original_url, expires_at, is_active, created_at, updated_at
`

type TryCreateLinkParams struct {
	Shortcode   string           `json:"shortcode"`
	OriginalUrl string           `json:"original_url"`
	UserID      string           `json:"user_id"`
	ExpiresAt   pgtype.Timestamp `json:"expires_at"`
}

type TryCreateLinkRow struct {
	ID          uuid.UUID        `json:"id"`
	Shortcode   string           `json:"shortcode"`
	OriginalUrl string           `json:"original_url"`
	ExpiresAt   pgtype.Timestamp `json:"expires_at"`
	IsActive    bool             `json:"is_active"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

// sqlc.arg(shortcode) sqlc.arg(original_url) sqlc.arg(user_id) sqlc.narg(expires_at)
func (q *Queries) TryCreateLink(ctx context.Context, arg TryCreateLinkParams) (TryCreateLinkRow, error) {
	row := q.db.QueryRow(ctx, tryCreateLink,
		arg.Shortcode,
		arg.OriginalUrl,
		arg.UserID,
		arg.ExpiresAt,
	)
	var i TryCreateLinkRow
	err := row.Scan(
		&i.ID,
		&i.Shortcode,
		&i.OriginalUrl,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET 
    shortcode = COALESCE($3, shortcode),
    is_active = COALESCE($4, is_active),
    expires_at = COALESCE($5, expires_at),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, shortcode, original_url, is_active, expires_at, created_at, updated_at
`

type UpdateLinkParams struct {
	ID        uuid.UUID        `json:"id"`
	UserID    string           `json:"user_id"`
	Shortcode *string          `json:"shortcode"`
	IsActive  *bool            `json:"is_active"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

type UpdateLinkRow struct {
	ID          uuid.UUID        `json:"id"`
	Shortcode   string           `json:"shortcode"`
	OriginalUrl string           `json:"original_url"`
	IsActive    bool             `json:"is_active"`
	ExpiresAt   pgtype.Timestamp `json:"expires_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (UpdateLinkRow, error) {
	row := q.db.QueryRow(ctx, updateLink,
		arg.ID,
		arg.UserID,
		arg.Shortcode,
		arg.IsActive,
		arg.ExpiresAt,
	)
	var i UpdateLinkRow
	err := row.Scan(
		&i.ID,
		&i.Shortcode,
		&i.OriginalUrl,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
