// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link_tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTagsToLink = `-- name: AddTagsToLink :exec
INSERT INTO link_tags (link_id, tag_id)
SELECT $1, t.id
FROM tags t
JOIN links l ON l.id = $1 AND l.user_id = $2 AND l.deleted_at IS NULL
WHERE t.id = ANY($3::uuid[]) AND t.user_id = $2
ON CONFLICT (link_id, tag_id) DO NOTHING
`

type AddTagsToLinkParams struct {
	LinkID uuid.UUID   `json:"link_id"`
	UserID string      `json:"user_id"`
	TagIDs []uuid.UUID `json:"tag_i_ds"`
}

// Adds owned tags to an owned link
func (q *Queries) AddTagsToLink(ctx context.Context, arg AddTagsToLinkParams) error {
	_, err := q.db.Exec(ctx, addTagsToLink, arg.LinkID, arg.UserID, arg.TagIDs)
	return err
}

const removeTagsFromLink = `-- name: RemoveTagsFromLink :exec
DELETE FROM link_tags lt
USING links l, tags t
WHERE lt.link_id = $1
  AND lt.tag_id = t.id
  AND l.id = lt.link_id
  AND l.user_id = $2
  AND l.deleted_at IS NULL
  AND t.user_id = $2
  AND t.id = ANY($3::uuid[])
`

type RemoveTagsFromLinkParams struct {
	LinkID uuid.UUID   `json:"link_id"`
	UserID string      `json:"user_id"`
	TagIDs []uuid.UUID `json:"tag_i_ds"`
}

// Removes owned tags from an owned link
func (q *Queries) RemoveTagsFromLink(ctx context.Context, arg RemoveTagsFromLinkParams) error {
	_, err := q.db.Exec(ctx, removeTagsFromLink, arg.LinkID, arg.UserID, arg.TagIDs)
	return err
}
