// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteLink = `-- name: DeleteLink :execrows
UPDATE links
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type DeleteLinkParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"user_id"`
}

func (q *Queries) DeleteLink(ctx context.Context, arg DeleteLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLink, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLinkByIdAndUser = `-- name: GetLinkByIdAndUser :one
SELECT id, shortcode, original_url, user_id, clicks, expires_at, created_at, updated_at, deleted_at FROM links
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
LIMIT 1
`

type GetLinkByIdAndUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"user_id"`
}

func (q *Queries) GetLinkByIdAndUser(ctx context.Context, arg GetLinkByIdAndUserParams) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByIdAndUser, arg.ID, arg.UserID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Shortcode,
		&i.OriginalUrl,
		&i.UserID,
		&i.Clicks,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLinkForRedirect = `-- name: GetLinkForRedirect :one
SELECT id, original_url, expires_at, clicks 
FROM links
WHERE shortcode = $1
AND deleted_at IS NULL
AND (expires_at IS NULL OR expires_at > NOW())
LIMIT 1
`

type GetLinkForRedirectRow struct {
	ID          uuid.UUID        `json:"id"`
	OriginalUrl string           `json:"original_url"`
	ExpiresAt   pgtype.Timestamp `json:"expires_at"`
	Clicks      *int32           `json:"clicks"`
}

func (q *Queries) GetLinkForRedirect(ctx context.Context, shortcode string) (GetLinkForRedirectRow, error) {
	row := q.db.QueryRow(ctx, getLinkForRedirect, shortcode)
	var i GetLinkForRedirectRow
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ExpiresAt,
		&i.Clicks,
	)
	return i, err
}

const incrementClicks = `-- name: IncrementClicks :exec
UPDATE links
SET clicks = clicks + 1
WHERE shortcode = $1 AND deleted_at IS NULL
`

func (q *Queries) IncrementClicks(ctx context.Context, shortcode string) error {
	_, err := q.db.Exec(ctx, incrementClicks, shortcode)
	return err
}

const listUserLinks = `-- name: ListUserLinks :many
SELECT id, shortcode, original_url, user_id, clicks, expires_at, created_at, updated_at, deleted_at FROM links
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListUserLinks(ctx context.Context, userID string) ([]Link, error) {
	rows, err := q.db.Query(ctx, listUserLinks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.Shortcode,
			&i.OriginalUrl,
			&i.UserID,
			&i.Clicks,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryCreateLink = `-- name: TryCreateLink :one
INSERT INTO links (shortcode, original_url, user_id)
SELECT $1::VARCHAR(20), $2::TEXT, $3::TEXT
WHERE NOT EXISTS (
    SELECT 1 FROM links 
    WHERE shortcode = $1::VARCHAR(20) AND deleted_at IS NULL
)
RETURNING id, shortcode, original_url, user_id, clicks, expires_at, created_at, updated_at, deleted_at
`

type TryCreateLinkParams struct {
	Shortcode   string `json:"shortcode"`
	OriginalUrl string `json:"original_url"`
	UserID      string `json:"user_id"`
}

// sqlc.arg(shortcode) sqlc.arg(original_url) sqlc.arg(user_id)
func (q *Queries) TryCreateLink(ctx context.Context, arg TryCreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, tryCreateLink, arg.Shortcode, arg.OriginalUrl, arg.UserID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Shortcode,
		&i.OriginalUrl,
		&i.UserID,
		&i.Clicks,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET 
    shortcode = COALESCE($3, shortcode),
    expires_at = COALESCE($4, expires_at),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, shortcode, original_url, user_id, clicks, expires_at, created_at, updated_at, deleted_at
`

type UpdateLinkParams struct {
	ID        uuid.UUID        `json:"id"`
	UserID    string           `json:"user_id"`
	Shortcode *string          `json:"shortcode"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLink,
		arg.ID,
		arg.UserID,
		arg.Shortcode,
		arg.ExpiresAt,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Shortcode,
		&i.OriginalUrl,
		&i.UserID,
		&i.Clicks,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
