// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM links
WHERE id = $1 AND user_id = $2
`

type DeleteLinkParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteLink(ctx context.Context, arg DeleteLinkParams) error {
	_, err := q.db.Exec(ctx, deleteLink, arg.ID, arg.UserID)
	return err
}

const getLinkByIdAndUser = `-- name: GetLinkByIdAndUser :one
SELECT id, code, original_url, user_id, clicks, expires_at, created_at, updated_at FROM links
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetLinkByIdAndUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetLinkByIdAndUser(ctx context.Context, arg GetLinkByIdAndUserParams) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByIdAndUser, arg.ID, arg.UserID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OriginalUrl,
		&i.UserID,
		&i.Clicks,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinkForRedirect = `-- name: GetLinkForRedirect :one
SELECT id, original_url, expires_at, clicks 
FROM links
WHERE code = $1
AND (expires_at IS NULL OR expires_at > NOW())
LIMIT 1
`

type GetLinkForRedirectRow struct {
	ID          uuid.UUID        `json:"id"`
	OriginalUrl string           `json:"original_url"`
	ExpiresAt   pgtype.Timestamp `json:"expires_at"`
	Clicks      *int32           `json:"clicks"`
}

func (q *Queries) GetLinkForRedirect(ctx context.Context, code string) (GetLinkForRedirectRow, error) {
	row := q.db.QueryRow(ctx, getLinkForRedirect, code)
	var i GetLinkForRedirectRow
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ExpiresAt,
		&i.Clicks,
	)
	return i, err
}

const incrementClicks = `-- name: IncrementClicks :exec
UPDATE links
SET clicks = clicks + 1
WHERE code = $1
`

func (q *Queries) IncrementClicks(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, incrementClicks, code)
	return err
}

const listUserLinks = `-- name: ListUserLinks :many
SELECT id, code, original_url, user_id, clicks, expires_at, created_at, updated_at FROM links
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserLinks(ctx context.Context, userID uuid.UUID) ([]Link, error) {
	rows, err := q.db.Query(ctx, listUserLinks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.OriginalUrl,
			&i.UserID,
			&i.Clicks,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryCreateLink = `-- name: TryCreateLink :one
INSERT INTO links (code, original_url, user_id)
VALUES ($1, $2, $3)
ON CONFLICT (code) DO NOTHING
RETURNING id, code, original_url, user_id, clicks, expires_at, created_at, updated_at
`

type TryCreateLinkParams struct {
	Code        string    `json:"code"`
	OriginalUrl string    `json:"original_url"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) TryCreateLink(ctx context.Context, arg TryCreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, tryCreateLink, arg.Code, arg.OriginalUrl, arg.UserID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OriginalUrl,
		&i.UserID,
		&i.Clicks,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET 
    code = COALESCE($3, code),
    expires_at = COALESCE($4, expires_at),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, code, original_url, user_id, clicks, expires_at, created_at, updated_at
`

type UpdateLinkParams struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	Code      *string          `json:"code"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLink,
		arg.ID,
		arg.UserID,
		arg.Code,
		arg.ExpiresAt,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OriginalUrl,
		&i.UserID,
		&i.Clicks,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
