// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link_tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTagsToLink = `-- name: AddTagsToLink :exec
INSERT INTO link_tags (link_id, tag_id)
SELECT $1, unnest($3::uuid[])
WHERE EXISTS (
    SELECT 1 FROM links l
    WHERE l.id = $1 AND l.user_id = $2 AND l.deleted_at IS NULL
)
AND EXISTS (
    SELECT 1 FROM tags t
    WHERE t.id = ANY($3::uuid[]) AND t.user_id = $2
)
ON CONFLICT (link_id, tag_id) DO NOTHING
`

type AddTagsToLinkParams struct {
	LinkID uuid.UUID   `json:"link_id"`
	UserID string      `json:"user_id"`
	TagIDs []uuid.UUID `json:"tag_i_ds"`
}

// Adds multiple tags to a link, ensuring both link and tags belong to the same user
func (q *Queries) AddTagsToLink(ctx context.Context, arg AddTagsToLinkParams) error {
	_, err := q.db.Exec(ctx, addTagsToLink, arg.LinkID, arg.UserID, arg.TagIDs)
	return err
}

const removeTagsFromLink = `-- name: RemoveTagsFromLink :exec
DELETE FROM link_tags
WHERE link_id = $1 
  AND tag_id = ANY($3::uuid[])
  AND EXISTS (
      SELECT 1 FROM links l
      WHERE l.id = $1 AND l.user_id = $2 AND l.deleted_at IS NULL
  )
  AND EXISTS (
      SELECT 1 FROM tags t
      WHERE t.id = ANY($3::uuid[]) AND t.user_id = $2
  )
`

type RemoveTagsFromLinkParams struct {
	LinkID uuid.UUID   `json:"link_id"`
	UserID string      `json:"user_id"`
	TagIDs []uuid.UUID `json:"tag_i_ds"`
}

// Removes multiple tags from a link, ensuring both link and tags belong to the same user
func (q *Queries) RemoveTagsFromLink(ctx context.Context, arg RemoveTagsFromLinkParams) error {
	_, err := q.db.Exec(ctx, removeTagsFromLink, arg.LinkID, arg.UserID, arg.TagIDs)
	return err
}
