// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID          uuid.UUID        `json:"id"`
	Code        string           `json:"code"`
	OriginalUrl string           `json:"original_url"`
	UserID      uuid.UUID        `json:"user_id"`
	Clicks      *int32           `json:"clicks"`
	ExpiresAt   pgtype.Timestamp `json:"expires_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID        `json:"id"`
	ClerkID   string           `json:"clerk_id"`
	Email     string           `json:"email"`
	Username  *string          `json:"username"`
	AvatarUrl *string          `json:"avatar_url"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
