// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, user_id)
VALUES ($1, $2)
RETURNING id, name, created_at, updated_at
`

type CreateTagParams struct {
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

type CreateTagRow struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (CreateTagRow, error) {
	row := q.db.QueryRow(ctx, createTag, arg.Name, arg.UserID)
	var i CreateTagRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :one
DELETE FROM tags
WHERE id = $1 AND user_id = $2
RETURNING id, name, created_at, updated_at
`

type DeleteTagParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"user_id"`
}

type DeleteTagRow struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) (DeleteTagRow, error) {
	row := q.db.QueryRow(ctx, deleteTag, arg.ID, arg.UserID)
	var i DeleteTagRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTags = `-- name: DeleteTags :many
DELETE FROM tags
WHERE id = ANY($1::uuid[]) AND user_id = $2
RETURNING id, name, created_at, updated_at
`

type DeleteTagsParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	UserID  string      `json:"user_id"`
}

type DeleteTagsRow struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) DeleteTags(ctx context.Context, arg DeleteTagsParams) ([]DeleteTagsRow, error) {
	rows, err := q.db.Query(ctx, deleteTags, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteTagsRow
	for rows.Next() {
		var i DeleteTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTags = `-- name: ListUserTags :many
SELECT id, name, created_at, updated_at FROM tags
WHERE user_id = $1
ORDER BY name
`

type ListUserTagsRow struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListUserTags(ctx context.Context, userID string) ([]ListUserTagsRow, error) {
	rows, err := q.db.Query(ctx, listUserTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserTagsRow
	for rows.Next() {
		var i ListUserTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET 
	name = $1, 
	updated_at = NOW()
WHERE id = $2 AND user_id = $3
RETURNING id, name, created_at, updated_at
`

type UpdateTagParams struct {
	Name   string    `json:"name"`
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"user_id"`
}

type UpdateTagRow struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (UpdateTagRow, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.Name, arg.ID, arg.UserID)
	var i UpdateTagRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
